set1 =set([x**2 for x in range(1,10)])
set2 = set([x**3 for x in range(1,10)])
print(set1)
print(set2)
set1.update(set2)
print(set1)
print(set1.pop())
set1.add(11)
print(set1)
set1.remove(16)
print(set1)
set1.clear()
print(set1)
'''In this program i have used some methods to update the set  '''